trigger:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
- name: baseUri
  type: string
  default: "https://app-p-mwsbackendpub-e15a9d34.azurewebsites.net"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '21.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    newman run ApiCollections/MWS-API-Tests.postman_collection.json --env-var baseUri="${{ parameters.baseUri }}"
  displayName: 'Run tests'
  env:
    CI: 'true'
