trigger:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
- name: baseUri
  type: string
  default: "postman-echo.com"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '21.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    newman run ApiCollections/example-collection.postman_collection.json \
      --env-var baseUri="${{ parameters.baseUri }}" \
      --reporters cli,junit \
      --reporter-junit-export $(Build.SourcesDirectory)/TestResults/testResults.xml
  displayName: 'Run tests'
  env:
    CI: 'true'

- task: PublishTestResults@2
  displayName: 'Publish API test results'
  inputs:
    testResultsFiles: '$(Build.SourcesDirectory)/TestResults/*.xml'